# Generated by Django 4.2.21 on 2025-08-30 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('neet_pg_inicet', 'NEET PG + INICET'), ('fmge', 'FMGE'), ('upsc_cms', 'UPSC CMS')], default='neet_pg_inicet', max_length=20)),
                ('plan_type', models.CharField(choices=[('monthly', '1 Month Plan'), ('quarterly', '3 Months Plan'), ('half_yearly', '6 Months Plan'), ('yearly', '12 Months Plan')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField()),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_most_popular', models.BooleanField(default=False)),
                ('is_best_value', models.BooleanField(default=False)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'ordering': ['category', 'duration_days'],
                'unique_together': {('category', 'plan_type')},
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('payu_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('upi', 'UPI'), ('wallet', 'Digital Wallet'), ('emi', 'EMI')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('gateway_response', models.JSONField(default=dict)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('mihpayid', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ref_num', models.CharField(blank=True, max_length=100, null=True)),
                ('bankcode', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_initiated', models.BooleanField(default=False)),
                ('payment_url_accessed', models.BooleanField(default=False)),
                ('payment_session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('one_time_token', models.CharField(blank=True, max_length=100, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivePlanConfiguration',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('custom_badge_text', models.CharField(blank=True, max_length=50, null=True)),
                ('promotional_text', models.CharField(blank=True, max_length=200, null=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_config', to='payments.paymentplan')),
            ],
            options={
                'ordering': ['plan__category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentplan')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymenttransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='payments_us_user_id_89dc0e_idx'), models.Index(fields=['user', 'plan'], name='payments_us_user_id_719f03_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('mihpayid',), name='unique_successful_mihpayid'),
        ),
    ]
