# Generated by Django 4.2.14 on 2024-08-16 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcqs.chapter'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcqs.subject'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcqs.unit'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcqs.topic'),
        ),
    ]
