# Generated by Django 4.2.14 on 2024-08-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0003_difficulties_mcq_types_mcq_difficulty_mcq_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['created_at']},
        ),
    ]
