# Generated by Django 4.2.14 on 2024-08-16 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0004_alter_subject_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
