# Generated by Django 4.2.14 on 2024-08-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0005_alter_subject_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['created_at']},
        ),
    ]
