# Generated by Django 4.2.14 on 2024-08-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0006_alter_chapter_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='unit',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
