# Generated by Django 4.2.14 on 2024-08-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0008_alter_chapter_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['subject', 'order']},
        ),
    ]
