# Generated by Django 4.2.14 on 2024-08-27 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcqs', '0010_remove_mcq_chapter_remove_mcq_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='correct_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='difficulty', to='mcqs.difficulties'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='text',
            field=models.TextField(default='Default question text'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='mcqs.mcq_types'),
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_uid', models.CharField(max_length=100)),
                ('selected_option', models.CharField(blank=True, max_length=10, null=True)),
                ('is_attempted', models.BooleanField(default=False)),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcqs.testsession')),
            ],
        ),
    ]
