# Generated by Django 4.2.14 on 2024-08-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0012_testanswer_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testanswer',
            old_name='number',
            new_name='timespent',
        ),
    ]
