# Generated by Django 4.2.14 on 2024-08-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0013_rename_number_testanswer_timespent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswer',
            name='timespent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
