# Generated by Django 4.2.14 on 2024-08-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0014_alter_testanswer_timespent'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
