# Generated by Django 4.2.14 on 2024-09-04 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0015_testsession_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='testsession',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
