# Generated by Django 4.2.14 on 2024-09-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0016_testsession_created_at_testsession_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='total_questions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
