# Generated by Django 4.2.14 on 2024-09-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0017_testsession_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='selected_optiontext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='timetaken',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
