# Generated by Django 4.2.14 on 2024-09-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0021_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark_type',
            field=models.CharField(choices=[('Star', 'Star'), ('Unstudied', 'Unstudied'), ('Other', 'Other')], max_length=10),
        ),
    ]
