# Generated by Django 4.2.14 on 2024-12-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0024_alter_bookmark_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='totaltime',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
