# Generated by Django 4.2.14 on 2025-01-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0026_mcq_correct_attempts_mcq_incorrect_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='mode_test',
            field=models.JSONField(default=list),
        ),
    ]
