# Generated by Django 4.2.14 on 2025-01-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0027_testsession_mode_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsession',
            name='mode_test',
        ),
        migrations.AddField(
            model_name='testsession',
            name='mode',
            field=models.TextField(blank=True),
        ),
    ]
