# Generated by Django 4.2.14 on 2025-01-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0028_remove_testsession_mode_test_testsession_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='mode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
