# Generated by Django 4.2.14 on 2025-01-21 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcqs', '0029_alter_testsession_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQFeedback',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_text', models.TextField()),
                ('feedback_type', models.CharField(choices=[('incorrect_answer', 'Incorrect Answer'), ('unclear_question', 'Unclear Question'), ('wrong_explanation', 'Wrong Explanation'), ('typo', 'Typo/Grammar'), ('image_issue', 'Image Issue'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='mcqs.mcq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
