# Generated by Django 4.2.14 on 2025-01-23 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0030_mcqfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
