# Generated by Django 4.2.14 on 2025-01-23 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0031_alter_testsession_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
