# Generated by Django 4.2.14 on 2025-02-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0032_alter_bookmark_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='mcqcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
