# Generated by Django 4.2.14 on 2025-02-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0033_mcq_mcqcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='pyq',
            field=models.BooleanField(default=False),
        ),
    ]
