# Generated by Django 4.2.14 on 2025-03-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0034_mcq_pyq'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='pyq_cat',
            field=models.CharField(blank=True, choices=[('NEET-PG', 'NEET PG'), ('INI-CET', 'INI-CET'), ('FMGE', 'FMGE')], max_length=100, null=True),
        ),
    ]
