# Generated by Django 4.2.14 on 2025-07-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0037_subject_icon_subject_icon_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.CharField(choices=[('fas fa-heart nfas', 'Heart - Cardiology/Medicine'), ('fas fa-brain', 'Brain - Neurology/Psychiatry'), ('fas fa-bone', 'Bone - Orthopedics'), ('fas fa-lungs', 'Lungs - Respiratory Medicine'), ('fas fa-eye', 'Eye - Ophthalmology'), ('fas fa-tooth', 'Tooth - Dentistry'), ('fas fa-baby', 'Baby - Pediatrics'), ('fas fa-female', 'Female - Gynecology'), ('fas fa-male', 'Male - Andrology'), ('fas fa-cut nfas', 'Cut - Surgery'), ('fas fa-deaf nfas', 'ENT - Otorhinolaryngology'), ('fas fa-pills', 'Pills - Pharmacology'), ('fas fa-microscope', 'Microscope - Pathology'), ('fas fa-dna', 'DNA - Genetics/Biochemistry'), ('fas fa-virus', 'Virus - Microbiology'), ('fas fa-radiation', 'Radiation - Radiology'), ('fas fa-syringe', 'Syringe - Anesthesia'), ('fas fa-user-md', 'Doctor - General Medicine'), ('fas fa-stethoscope', 'Stethoscope - General'), ('fas fa-heartbeat', 'Heartbeat - Physiology'), ('fas fa-flask', 'Flask - Biochemistry'), ('fas fa-notes-medical', 'Medical Notes - Medicine'), ('fas fa-x-ray', 'X-Ray - Radiology'), ('fas fa-ambulance', 'Ambulance - Emergency Medicine'), ('fas fa-hand-holding-medical', 'Hand Medical - General Care'), ('fas fa-clinic-medical', 'Clinic - General Medicine')], default='fas fa-stethoscope', help_text='FontAwesome icon class for this subject', max_length=50),
        ),
    ]
