# Generated by Django 4.2.21 on 2025-08-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0038_alter_subject_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='hig_yield',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsession',
            name='pyq',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='pyq_cat',
            field=models.CharField(blank=True, choices=[('NEET-PG Pattern', 'NEET PG Pattern'), ('INI-CET', 'INI-CET'), ('FMGE', 'FMGE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.CharField(choices=[('fas fa-heart nfas', 'Heart - Cardiology/Medicine'), ('fas fa-brain', 'Brain - Neurology/Psychiatry'), ('fas fa-bone', 'Bone - Orthopedics'), ('fas fa-lungs', 'Lungs - Respiratory Medicine'), ('fas fa-eye', 'Eye - Ophthalmology'), ('fas fa-tooth', 'Tooth - Dentistry'), ('fas fa-baby', 'Baby - Pediatrics'), ('fas fa-female', 'Female - Gynecology'), ('fas fa-male', 'Male - Andrology'), ('fas fa-cut nfas', 'Cut - Surgery'), ('fas fa-pills', 'Pills - Pharmacology'), ('fas fa-microscope', 'Microscope - Pathology'), ('fas fa-dna', 'DNA - Genetics/Biochemistry'), ('fas fa-virus', 'Virus - Microbiology'), ('fas fa-radiation', 'Radiation - Radiology'), ('fas fa-syringe', 'Syringe - Anesthesia'), ('fas fa-user-md', 'Doctor - General Medicine'), ('fas fa-stethoscope', 'Stethoscope - General'), ('fas fa-heartbeat', 'Heartbeat - Physiology'), ('fas fa-flask', 'Flask - Biochemistry'), ('fas fa-notes-medical', 'Medical Notes - Medicine'), ('fas fa-x-ray', 'X-Ray - Radiology'), ('fas fa-ambulance', 'Ambulance - Emergency Medicine'), ('fas fa-hand-holding-medical', 'Hand Medical - General Care'), ('fas fa-clinic-medical', 'Clinic - General Medicine')], default='fas fa-stethoscope', help_text='FontAwesome icon class for this subject', max_length=50),
        ),
    ]
