# Generated by Django 4.2.14 on 2025-03-15 06:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mcqs', '0034_mcq_pyq'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestCategory',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(choices=[('NEET-PG', 'NEET PG'), ('INI-CET', 'INI-CET'), ('FMGE', 'FMGE')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mock Test Categories',
            },
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('test_type', models.CharField(choices=[('FULL', 'Full Syllabus'), ('SUBJECT', 'Subject Specific')], max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('time_limit_minutes', models.PositiveIntegerField(default=180)),
                ('is_active', models.BooleanField(default=True)),
                ('total_mcqs', models.PositiveIntegerField(default=180)),
                ('percent_pyq', models.PositiveIntegerField(default=0)),
                ('percent_easy', models.PositiveIntegerField(default=33)),
                ('percent_medium', models.PositiveIntegerField(default=34)),
                ('percent_hard', models.PositiveIntegerField(default=33)),
                ('mcq_types_distribution', models.JSONField(blank=True, default=dict, null=True)),
                ('subject_distribution', models.JSONField(blank=True, default=dict, null=True)),
                ('percent_most_correct', models.PositiveIntegerField(default=0)),
                ('percent_most_incorrect', models.PositiveIntegerField(default=0)),
                ('seed', models.PositiveIntegerField(default=0, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to='mocktest.mocktestcategory')),
                ('subjects', models.ManyToManyField(blank=True, related_name='mock_tests', to='mcqs.subject')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MockTestMCQ',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to='mcqs.mcq')),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_mcqs', to='mocktest.mocktest')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('mock_test', 'mcq')},
            },
        ),
    ]
