# Generated by Django 4.2.14 on 2025-03-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
