# Generated by Django 4.2.14 on 2025-03-15 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0034_mcq_pyq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mocktest', '0002_mocktest_total_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockSession',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_graded', models.BooleanField(default=False)),
                ('total_attempted', models.PositiveIntegerField(default=0)),
                ('total_correct', models.PositiveIntegerField(default=0)),
                ('total_incorrect', models.PositiveIntegerField(default=0)),
                ('total_skipped', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('percentile', models.FloatField(blank=True, null=True)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('terminated_by_user', models.BooleanField(default=False)),
                ('terminated_by_timeout', models.BooleanField(default=False)),
                ('terminated_by_browser_close', models.BooleanField(default=False)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mocktest.mocktest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
                'unique_together': {('user', 'mock_test')},
            },
        ),
        migrations.CreateModel(
            name='MockAnswer',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('is_marked_for_review', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_answers', to='mcqs.mcq')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mocktest.mocksession')),
            ],
            options={
                'ordering': ['session', 'mcq'],
                'unique_together': {('session', 'mcq')},
            },
        ),
    ]
