# Generated by Django 4.2.14 on 2025-03-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0003_mocksession_mockanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockanswer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
