# Generated by Django 4.2.14 on 2025-03-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0004_alter_mockanswer_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocksession',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
