# Generated by Django 4.2.14 on 2025-03-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0005_mocksession_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockanswer',
            name='visible_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
