# Generated by Django 4.2.14 on 2025-07-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0006_mockanswer_visible_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktest',
            name='mcq_types_distribution',
            field=models.JSONField(blank=True, default=dict, help_text="JSON object with MCQ type names as keys and percentages as values. Example: {'Image': 40, 'General': 30, 'Clinical': 30}", null=True),
        ),
        migrations.AlterField(
            model_name='mocktestcategory',
            name='name',
            field=models.CharField(choices=[('NEET-PG Pattern', 'NEET PG Pattern'), ('INI-CET', 'INI-CET'), ('FMGE', 'FMGE')], max_length=100),
        ),
    ]
