# Generated by Django 4.2.14 on 2024-10-22 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0002_shared_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_bookmark',
            name='shared_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
