# Generated by Django 4.2.14 on 2024-10-24 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0003_alter_shared_bookmark_shared_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_test',
            name='shared_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
