# Generated by Django 4.2.14 on 2025-01-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0004_alter_shared_test_shared_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_test',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
