# Generated by Django 4.2.14 on 2025-01-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0005_shared_test_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_test',
            name='new_test',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
