# Generated by Django 4.2.14 on 2025-01-23 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0006_shared_test_new_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_bookmark',
            name='shared_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shared_test',
            name='shared_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
