# Generated by Django 4.2.14 on 2024-10-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_solved_mcqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='solved_mcqs',
        ),
    ]
