# Generated by Django 4.2.14 on 2024-10-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_solved_mcqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
