# Generated by Django 4.2.14 on 2024-12-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
