# Generated by Django 4.2.14 on 2025-03-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_notification_pushnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotification',
            name='notification_ptr',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PushNotification',
        ),
    ]
