# Generated by Django 4.2.14 on 2025-07-09 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0006_mockanswer_visible_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcqs', '0037_subject_icon_subject_icon_color'),
        ('accounts', '0012_visitorcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='hive_current_test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mock_current_test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_medical_college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('new_mock', 'New Mock Test Available'), ('mock_rank', 'Mock Test Rank Updated'), ('incomplete_mock', 'Incomplete Mock Test'), ('incomplete_practice', 'Incomplete Practice Session'), ('practice_reminder', 'Practice Reminder'), ('mock_reminder', 'Mock Test Reminder'), ('streak', 'Practice Streak'), ('feedback_response', 'Feedback Response')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('related_mock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='mocktest.mocktest')),
                ('related_practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='mcqs.testsession')),
                ('related_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_notifications', to='mocktest.mocksession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('established', models.IntegerField(help_text='Year of establishment')),
                ('university', models.CharField(max_length=255)),
                ('ownership', models.CharField(choices=[('government_india', 'Government of India'), ('government_state', 'State Government'), ('private', 'Private'), ('autonomous', 'Autonomous')], max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='accounts.state')),
            ],
            options={
                'verbose_name': 'Medical College',
                'verbose_name_plural': 'Medical Colleges',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='medical_college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.medicalcollege'),
        ),
    ]
