# Generated by Django 4.2.14 on 2025-12-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_free_mcq_attempted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='flashcard_free_sessions',
            field=models.IntegerField(default=0, help_text='Number of free flashcard sessions attempted by the user'),
        ),
    ]
