# Generated by Django 4.2.14 on 2025-12-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_flashcard_free_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10, unique=True)),
                ('current_version', models.CharField(help_text='e.g., 1.2.0', max_length=20)),
                ('minimum_version', models.CharField(help_text='Minimum version required to run', max_length=20)),
                ('download_url', models.URLField(help_text='URL to download latest APK/App')),
                ('force_update', models.BooleanField(default=False, help_text='Force users to update')),
                ('update_message', models.TextField(default='A new version is available! Please update for the best experience.', help_text='Message shown to users')),
                ('whats_new', models.TextField(blank=True, help_text='Release notes')),
                ('is_maintenance', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, default='App is under maintenance. Please try again later.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
