# Generated by Django 4.2.14 on 2025-12-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='apk_file',
            field=models.FileField(blank=True, help_text='Upload APK file directly (optional - will use this instead of download_url if provided)', null=True, upload_to='apk/'),
        ),
        migrations.AddField(
            model_name='appversion',
            name='banner_text',
            field=models.CharField(default='Download MCQwave Android App - Practice Offline!', help_text='Banner text shown to users', max_length=200),
        ),
        migrations.AddField(
            model_name='appversion',
            name='show_download_banner',
            field=models.BooleanField(default=True, help_text='Display download banner on landing page'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='download_url',
            field=models.URLField(blank=True, help_text='External URL to download APK (used if apk_file is not provided)', null=True),
        ),
    ]
