# Generated by Django 4.2.14 on 2025-11-17 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(default='book', max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flashcards_subject',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('total_xp', models.IntegerField(default=0)),
                ('total_cards_studied', models.IntegerField(default=0)),
                ('daily_goal', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flashcards_user_streak',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='flashcards.subject')),
            ],
            options={
                'db_table': 'flashcards_unit',
                'ordering': ['display_order', 'name'],
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='flashcards.unit')),
            ],
            options={
                'db_table': 'flashcards_topic',
                'ordering': ['display_order', 'name'],
                'unique_together': {('unit', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('today', "Today's Session"), ('topic', 'Topic Focus'), ('weak', 'Weak Topics'), ('mixed', 'Mixed Review'), ('custom', 'Custom Session')], default='today', max_length=20)),
                ('cards_reviewed', models.IntegerField(default=0)),
                ('cards_correct', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flashcards.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flashcards_study_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('clinical', 'Clinical Case'), ('concept', 'Concept'), ('image', 'Image-based'), ('mnemonic', 'Mnemonic'), ('integrated', 'Integrated MCQ')], default='concept', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='moderate', max_length=20)),
                ('front_text', models.TextField(help_text='Question/Prompt')),
                ('back_text', models.TextField(help_text='Answer/Explanation')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='flashcards/images/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='flashcards/images/')),
                ('mnemonic', models.TextField(blank=True, null=True)),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('references', models.TextField(blank=True, null=True)),
                ('linked_mcq_uids', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.topic')),
            ],
            options={
                'db_table': 'flashcards_flashcard',
                'ordering': ['topic', 'difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(default='#fbbf24', max_length=7)),
                ('criteria_type', models.CharField(max_length=50)),
                ('criteria_value', models.IntegerField()),
                ('xp_reward', models.IntegerField(default=100)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcards.subject')),
            ],
            options={
                'db_table': 'flashcards_badge',
            },
        ),
        migrations.CreateModel(
            name='UserFlashcardProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('repetitions', models.IntegerField(default=0)),
                ('interval', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('reviewed', 'Reviewed'), ('mastered', 'Mastered')], default='new', max_length=20)),
                ('last_rating', models.IntegerField(blank=True, choices=[(0, 'Complete Blackout'), (1, 'Incorrect - Correct Seemed Easy'), (2, 'Incorrect - Remembered with Difficulty'), (3, 'Correct - Serious Difficulty'), (4, 'Correct - Hesitation'), (5, 'Perfect Response')], null=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('user_note', models.TextField(blank=True, null=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_reviews', models.IntegerField(default=0)),
                ('correct_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='flashcards.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flashcards_user_progress',
                'indexes': [models.Index(fields=['user', 'next_review'], name='flashcards__user_id_728d31_idx'), models.Index(fields=['user', 'status'], name='flashcards__user_id_5c220c_idx'), models.Index(fields=['next_review'], name='flashcards__next_re_e33db1_idx'), models.Index(fields=['user', 'is_bookmarked'], name='flashcards__user_id_2c84e7_idx')],
                'unique_together': {('user', 'flashcard')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flashcards_user_badge',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['topic', 'card_type'], name='flashcards__topic_i_2e5eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['difficulty'], name='flashcards__difficu_6a638b_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['created_at'], name='flashcards__created_43dd56_idx'),
        ),
    ]
