# Generated by Django 4.2.21 on 2025-08-30 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mcqs', '0039_mcq_hig_yield_testsession_pyq_alter_mcq_pyq_cat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='difficulties',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='mcq_types',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('types', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(choices=[('fas fa-heart', 'Heart - Cardiology/Medicine'), ('fas fa-brain', 'Brain - Neurology/Psychiatry'), ('fas fa-bone', 'Bone - Orthopedics'), ('fas fa-lungs', 'Lungs - Respiratory Medicine'), ('fas fa-eye', 'Eye - Ophthalmology'), ('fas fa-tooth', 'Tooth - Dentistry'), ('fas fa-baby', 'Baby - Pediatrics'), ('fas fa-female', 'Female - Gynecology'), ('fas fa-male', 'Male - Andrology'), ('fas fa-cut', 'Cut - Surgery'), ('fas fa-pills', 'Pills - Pharmacology'), ('fas fa-microscope', 'Microscope - Pathology'), ('fas fa-dna', 'DNA - Genetics/Biochemistry'), ('fas fa-virus', 'Virus - Microbiology'), ('fas fa-radiation', 'Radiation - Radiology'), ('fas fa-syringe', 'Syringe - Anesthesia'), ('fas fa-user-md', 'Doctor - General Medicine'), ('fas fa-stethoscope', 'Stethoscope - General'), ('fas fa-heartbeat', 'Heartbeat - Physiology'), ('fas fa-flask', 'Flask - Biochemistry'), ('fas fa-notes-medical', 'Medical Notes - Medicine'), ('fas fa-x-ray', 'X-Ray - Radiology'), ('fas fa-ambulance', 'Ambulance - Emergency Medicine'), ('fas fa-hand-holding-medical', 'Hand Medical - General Care'), ('fas fa-clinic-medical', 'Clinic - General Medicine')], default='fas fa-stethoscope', help_text='FontAwesome icon class for this subject', max_length=50)),
                ('icon_color', models.CharField(default='#1e3c72', help_text='Hex color code for the icon (e.g., #007bff)', max_length=20)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='pyqs.subject')),
            ],
            options={
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PYQ',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_input', models.TextField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, help_text='Topic name for this question', max_length=255, null=True)),
                ('text', models.TextField(default='Default question text')),
                ('option_1', models.CharField(blank=True, max_length=255, null=True)),
                ('option_2', models.CharField(blank=True, max_length=255, null=True)),
                ('option_3', models.CharField(blank=True, max_length=255, null=True)),
                ('option_4', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_option', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pyq_images/')),
                ('correct_attempts', models.IntegerField(default=0)),
                ('incorrect_attempts', models.IntegerField(default=0)),
                ('pyqcode', models.CharField(blank=True, max_length=255, null=True)),
                ('hig_yield', models.BooleanField(default=False)),
                ('pyq', models.BooleanField(default=True)),
                ('pyq_cat', models.CharField(blank=True, choices=[('NEET-PG', 'NEET-PG'), ('INI-CET', 'INI-CET'), ('FMGE', 'FMGE'), ('UPSC-CMS', 'UPSC-CMS')], max_length=100, null=True)),
                ('pyq_year', models.CharField(blank=True, choices=[('', '--------'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='', max_length=4)),
                ('pyq_month', models.CharField(blank=True, choices=[('', '--------'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='', help_text='Optional: Month for exams that occur multiple times per year (e.g., INI-CET, FMGE)', max_length=20)),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pyq_difficulty', to='pyqs.difficulties')),
                ('types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pyq_type', to='pyqs.mcq_types')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pyqs', to='pyqs.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PYQBookmark',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('bkmk_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bookmark_type', models.CharField(choices=[('Star', 'Star'), ('Unstudied', 'Unstudied'), ('Other', 'Other')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pyq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyqs.pyq')),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcqs.testsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'pyq', 'test_session')},
            },
        ),
    ]
